### ISSUE TITLE
Error in the documentation?

### ISSUE THREAD

**Issue by quark67** [joaomlourenco/stocksize#2]
On lines 113-114 of https://github.com/joaomlourenco/stocksize/blob/main/stocksize-doc.tex, we read:

```tex
\newstocksize{layoutsize={15cm,10cm},margin=1.5cm}
 \printpagesize[15cm, 10cm, margin=1cm]
```

Are the two differents values for margin (1.5cm and 1cm) deliberate, or is it a mistake?

Same for lines 118-119:

```tex
\newstocksize{layoutsize={20cm,20cm},margin=4.0cm}
\printpagesize[20cm, 20cm, margin=1cm]
```

Here, the difference is clear in the PDF, the margin is not 1cm, but it is printed that the margin is 1cm (page 7 of the PDF):
<img width="827" alt="image" src="https://github.com/user-attachments/assets/aa40fa4a-7924-4689-a625-216c36e872d9">

**Comment by joaomlourenco** [comment]
Fixed in v1.0.3.
